import type { OrderContent } from "./content.types";

export const orderContent = {
  heading: {
    title: "Tabla Simple Sushi",
  },
  reserveHeading: "Reservá tu tabla para el fin de semana",
  gallery: {
    label: "Product images",
    viewLabel: "View product image",
    featured: {
      src: "/brand/hero/hero-table.png",
      alt: "Tabla surtida de sushi lista para compartir",
    },
    thumbnails: [
      {
        src: "/brand/products/langostino-roll.png",
        alt: "Pieza de langostino de la tabla",
      },
      {
        src: "/brand/products/atun-roll.png",
        alt: "Pieza de atún de la tabla",
      },
      {
        src: "/brand/products/salmon-roll.png",
        alt: "Pieza de salmón de la tabla",
      },
    ],
  },
  steps: {
    size: {
      label: "1. ELEGIR TAMAÑO",
    },
    date: {
      label: "2. FECHA DE ENTREGA",
    },
    slot: {
      label: "3. FRANJA HORARIA",
    },
    address: {
      label: "4. DIRECCIÓN DE ENVÍO",
    },
    customer: {
      label: "5. DATOS DEL CLIENTE",
    },
    payment: {
      label: "6. MÉTODO DE PAGO",
    },
  },
  productName: "Tabla Simple Sushi",
  recommendedBadge: "Recomendada",
  availabilityNotes: {
    available: "Disponible",
    soldOut: "Agotado",
  },
  cta: "Reservar mi tabla",
  buyLabel: "Continuar",
  addressField: {
    label: "Dirección de envío",
    placeholder: "Ej: Av. San Martín 1234",
    helper: "Envío gratuito exclusivo en Alejandro Korn (radio 3km).",
    requiredMessage: "Ingresá tu dirección para continuar.",
  },
  betweenStreetsField: {
    label: "Entre calles",
    placeholder: "Ej: entre Mitre y Belgrano",
  },
  floorField: {
    label: "Piso/Depto",
    placeholder: "Ej: 2° C",
    optionalHint: "Opcional",
  },
  referenceField: {
    label: "Referencia",
    placeholder: "Ej: casa de rejas negras",
    optionalHint: "Opcional",
  },
  customerNameField: {
    label: "Nombre",
    placeholder: "Tu nombre",
    requiredMessage: "Ingresá tu nombre para continuar.",
  },
  phoneField: {
    label: "Teléfono",
    placeholder: "Ej: 11 2345 6789",
    optionalHint: "Opcional",
    helper: "Lo usamos solo si necesitamos avisarte algo sobre la entrega.",
  },
  dialog: {
    title: "Confirmá tu pedido",
    subtitle: "Revisá los detalles antes de enviarlo por WhatsApp.",
    sizeLabel: "Tamaño",
    productLineLabelSingular: "Tabla de",
    productLineLabelPlural: "Tablas de",
    dateLabel: "Día",
    slotLabel: "Horario",
    addressLabel: "Dirección",
    betweenStreetsLabel: "Entre calles",
    floorLabel: "Piso/Depto",
    referenceLabel: "Referencia",
    customerNameLabel: "Nombre",
    phoneLabel: "Teléfono",
    paymentMethodLabel: "Método de pago",
    subtotalLabel: "Subtotal",
    deliveryLabel: "Envío",
    coverageLabel: "Cobertura",
    totalLabel: "TOTAL",
    freeDeliveryValue: "Gratis",
    coverageValue: "Hasta 3 km",
    footnote:
      "El pedido se confirma por WhatsApp cuando enviás el mensaje. No realizaremos ningún cobro desde esta plataforma.",
    backLabel: "Volver y editar",
    confirmLabel: "Enviar pedido por WhatsApp",
    closeLabel: "Cerrar",
    paymentMethodCashLabel: "Efectivo",
    paymentMethodTransferLabel: "Transferencia",
  },
  wizard: {
    editLabel: "Editar",
    continueLabel: "Continuar",
    backLabel: "Volver",
    stepDateTitle: "Fecha y horario",
    stepAddressTitle: "Dirección de envío",
    stepCustomerTitle: "Datos del cliente",
    stepPaymentTitle: "Método de pago",
    stepSummaryTitle: "Confirmá tu pedido",
    summaryButtonLabel: "Enviar pedido por WhatsApp",
    totalPiecesLabel: "Total de piezas",
    totalLabel: "Total",
    addLabel: "Agregar una tabla de",
    removeLabel: "Quitar una tabla de",
    limitMessage: "Hasta 300 piezas por pedido",
  },
  message: {
    defaultGreeting: "Hola 👋",
    greeting: "Hola! Quiero hacer un pedido de Simple Sushi 🍣",
    orderSection: "Pedido",
    orderSectionIcon: "📋",
    sizeLabel: "Tabla",
    dayLabel: "Día",
    slotLabel: "Horario",
    totalLabel: "Total",
    piecesLabel: "piezas",
    deliverySection: "Entrega",
    deliverySectionIcon: "📍",
    addressLabel: "Dirección",
    betweenStreetsLabel: "Entre calles",
    floorLabel: "Piso/Depto",
    referenceLabel: "Referencia",
    paymentSection: "Pago",
    paymentSectionIcon: "💲",
    paymentLabel: "Método de pago",
    contactSection: "Datos de contacto",
    contactSectionIcon: "👤",
    phoneLabel: "Teléfono",
    closing: "¿Podés confirmarme el pedido?",
  },
} satisfies OrderContent;
