import type { OrderContent } from "./content.types";

export const orderContent = {
  heading: {
    title: "Tabla Simple Sushi",
  },
  customOrder: {
    eyebrow: "Experiencia a tu medida",
    title: "Creá una tabla",
    highlight: "única para vos",
    description:
      "Elegí tus piezas favoritas, combiná sabores y armá una experiencia gastronómica hecha exactamente a tu gusto.",
    cta: "Personalizá tu tabla",
    helper: "Rápido, simple y 100% personalizado",
    badge: "Sushi hecho a tu medida",
    steps: [
      {
        number: "01",
        title: "Elegí tus piezas",
        description: "Seleccioná tus favoritos",
      },
      {
        number: "02",
        title: "Combiná sabores",
        description: "Armá la mezcla ideal",
      },
      {
        number: "03",
        title: "Disfrutá",
        description: "Nosotros hacemos el resto",
      },
    ],
  },
  flavorBreakdown: {
    includesLabel: "Incluye",
    flavorCountLabel: "Sabores",
    unitLabel: "un.",
  },
  customOrderModal: {
    titleLabel: "Personalizá tu tabla",
    stepLabel: "Paso {step} de 3",
    piecesLabel: "Piezas",
    pieceOptionLabel: "{p} piezas",
    flavorLimitLabel: "Elegí hasta {maxFlavors} sabores",
    selectedCountLabel: "Seleccionados: {selected}/{max}",
    quantityLabel: "Cantidad por sabor",
    remainingPiecesLabel: "Te quedan: {remaining} piezas",
    distributeEvenlyLabel: "Repartir parejo",
    estimatedPriceLabel: "Precio estimado",
    assignedPiecesLabel: "{assigned}/{total} piezas",
    confirmButtonLabel: "Confirmar",
  },
  reserveHeading: "Reservá tu tabla para el fin de semana",
  gallery: {
    label: "Product images",
    viewLabel: "View product image",
    prevLabel: "Previous image",
    nextLabel: "Next image",
    featured: {
      src: "/brand/hero/hero-table.png",
      alt: "Tabla surtida de sushi lista para compartir",
    },
    thumbnails: [
      {
        src: "/brand/products/philadelphia-roll.png",
        alt: "Sabor NewYork Philly",
      },
      {
        src: "/brand/products/salmon-roll.png",
        alt: "Sabor Salmón cocido",
      },
      {
        src: "/brand/products/atun-roll.png",
        alt: "Sabor Tuna",
      },
      {
        src: "/brand/products/langostino-roll.png",
        alt: "Sabor Pollo y verdeo",
      },
      {
        src: "/brand/products/veggie-roll.png",
        alt: "Sabor Zanahoria",
      },
      {
        src: "/brand/products/veggie-roll.png",
        alt: "Sabor Pepino",
      },
      {
        src: "/brand/products/veggie-roll.png",
        alt: "Sabor Remolacha",
      },
      {
        src: "/brand/products/kani-roll.png",
        alt: "Sabor Huevo",
      },
    ],
  },
  steps: {
    size: {
      label: "1. ELEGIR TAMAÑO",
    },
    date: {
      label: "2. FECHA DE ENTREGA",
    },
    slot: {
      label: "3. FRANJA HORARIA",
    },
    address: {
      label: "4. DIRECCIÓN DE ENVÍO",
    },
    customer: {
      label: "5. DATOS DEL CLIENTE",
    },
    payment: {
      label: "6. MÉTODO DE PAGO",
    },
  },
  productName: "Tabla Simple Sushi",
  recommendedBadge: "Recomendada",
  availabilityNotes: {
    available: "Disponible",
    soldOut: "Agotado",
  },
  cta: "Reservar mi tabla",
  buyLabel: "Continuar",
  addressField: {
    label: "Dirección de envío",
    placeholder: "Ej: Av. San Martín 1234",
    helper: "Envío gratuito exclusivo en Alejandro Korn (radio 3km).",
    requiredMessage: "Ingresá tu dirección para continuar.",
  },
  betweenStreetsField: {
    label: "Entre calles",
    placeholder: "Ej: entre Mitre y Belgrano",
  },
  floorField: {
    label: "Piso/Depto",
    placeholder: "Ej: 2° C",
    optionalHint: "Opcional",
  },
  referenceField: {
    label: "Referencia",
    placeholder: "Ej: casa de rejas negras",
    optionalHint: "Opcional",
  },
  customerNameField: {
    label: "Nombre",
    placeholder: "Tu nombre",
    requiredMessage: "Ingresá tu nombre para continuar.",
  },
  phoneField: {
    label: "Teléfono",
    placeholder: "Ej: 11 2345 6789",
    optionalHint: "Opcional",
    helper: "Lo usamos solo si necesitamos avisarte algo sobre la entrega.",
  },
  dialog: {
    title: "Confirmá tu pedido",
    subtitle: "Revisá los detalles antes de enviarlo por WhatsApp.",
    sizeLabel: "Tamaño",
    productLineLabelSingular: "Tabla de",
    productLineLabelPlural: "Tablas de",
    dateLabel: "Día",
    slotLabel: "Horario",
    addressLabel: "Dirección",
    betweenStreetsLabel: "Entre calles",
    floorLabel: "Piso/Depto",
    referenceLabel: "Referencia",
    customerNameLabel: "Nombre",
    phoneLabel: "Teléfono",
    paymentMethodLabel: "Método de pago",
    subtotalLabel: "Subtotal",
    deliveryLabel: "Envío",
    coverageLabel: "Cobertura",
    totalLabel: "TOTAL",
    freeDeliveryValue: "Gratis",
    coverageValue: "Hasta 3 km",
    footnote:
      "El pedido se confirma por WhatsApp cuando enviás el mensaje. No realizaremos ningún cobro desde esta plataforma.",
    backLabel: "Volver y editar",
    confirmLabel: "Enviar pedido por WhatsApp",
    closeLabel: "Close",
    paymentMethodCashLabel: "Efectivo",
    paymentMethodTransferLabel: "Transferencia",
  },
  wizard: {
    editLabel: "Editar",
    continueLabel: "Continuar",
    backLabel: "Volver",
    stepDateTitle: "Fecha y horario",
    stepAddressTitle: "Dirección de envío",
    stepCustomerTitle: "Datos del cliente",
    stepPaymentTitle: "Método de pago",
    stepSummaryTitle: "Confirmá tu pedido",
    summaryButtonLabel: "Enviar pedido por WhatsApp",
    totalPiecesLabel: "Total de piezas",
    totalLabel: "Total",
    addLabel: "Add a table of",
    removeLabel: "Remove a table of",
    limitMessage: "Hasta 300 piezas por pedido",
  },
  message: {
    defaultGreeting: "Hola 👋",
    greeting: "Hola! Quiero hacer un pedido de Simple Sushi 🍣",
    orderSection: "Pedido",
    orderSectionIcon: "📋",
    sizeLabel: "Tabla",
    dayLabel: "Día",
    slotLabel: "Horario",
    totalLabel: "Total",
    piecesLabel: "piezas",
    deliverySection: "Entrega",
    deliverySectionIcon: "📍",
    addressLabel: "Dirección",
    betweenStreetsLabel: "Entre calles",
    floorLabel: "Piso/Depto",
    referenceLabel: "Referencia",
    paymentSection: "Pago",
    paymentSectionIcon: "💲",
    paymentLabel: "Método de pago",
    contactSection: "Datos de contacto",
    contactSectionIcon: "👤",
    phoneLabel: "Teléfono",
    closing: "¿Podés confirmarme el pedido?",
  },
} satisfies OrderContent;
